//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Domain.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string TheAmountShouldBePositive {
            get {
                return ResourceManager.GetString("TheAmountShouldBePositive", resourceCulture);
            }
        }
        
        internal static string CreditIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("CreditIdCannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string TheTextFieldIsRequired {
            get {
                return ResourceManager.GetString("TheTextFieldIsRequired", resourceCulture);
            }
        }
        
        internal static string DebitIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("DebitIdCannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string InvalidTextFormat {
            get {
                return ResourceManager.GetString("InvalidTextFormat", resourceCulture);
            }
        }
        
        internal static string AccountIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("AccountIdCannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string CustomerIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("CustomerIdCannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string AccountHasNotEnoughFunds {
            get {
                return ResourceManager.GetString("AccountHasNotEnoughFunds", resourceCulture);
            }
        }
    }
}
